# Generated by Django 4.2.7 on 2023-11-21 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'verbose_name': 'День', 'verbose_name_plural': 'Дни'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписания'},
        ),
    ]
