# Generated by Django 4.2.7 on 2023-11-21 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_shedule', '0003_rename_friday_time_end_day_day_time_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_shedule.schedule', verbose_name='Расписание'),
            preserve_default=False,
        ),
    ]
