# Generated by Django 4.2.7 on 2023-11-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shedule', '0004_day_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='week_day',
            field=models.CharField(default=0, max_length=200, verbose_name='День недели'),
        ),
        migrations.AddConstraint(
            model_name='day',
            constraint=models.UniqueConstraint(fields=('week_day', 'schedule'), name='app_shedule_day_week_day_schedule'),
        ),
    ]
