# Generated by Django 4.2.7 on 2023-11-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shedule', '0006_alter_day_break_in_schedule_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='strict_schedule',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='type_schedule',
            field=models.CharField(help_text='\n        Выберите тип расписания.<br>\n        Расписание может быть создано как для Сотрудника, так и для Профиля доступа,<br>\n        а так же и для Проходной. Это дает еще один уровень контроля. Например:<br>\n        созданное расписание для сотрудников будет оповещать дежурного/охрану/вахтера<br>\n        о времени действия сотрудника, скажем, что последний зашел с опозданием или вне графика.<br>\n        Создав и добавив расписание для проходной, пост будет информирован о том,<br>\n        что событие было совершено согласно расписанию проходной или вне расписания.<br>\n        ', max_length=100, verbose_name='Тип расписания'),
        ),
    ]
