# Generated by Django 4.2.7 on 2023-11-27 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shedule', '0007_remove_schedule_strict_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='type_schedule',
        ),
    ]
