# Generated by Django 4.2.7 on 2023-12-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_checkpoint', '0005_remove_checkpoint_checpoint_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor_name', models.CharField(default='Монитор [-укажи имя-]', max_length=125, verbose_name='Имя монитора')),
                ('monitor_checkpoint', models.ManyToManyField(blank=True, to='app_checkpoint.checkpoint')),
            ],
            options={
                'verbose_name': 'Монитор',
                'verbose_name_plural': 'Мониторы',
            },
        ),
    ]
