# Generated by Django 4.2.7 on 2023-12-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_checkpoint', '0005_remove_checkpoint_checpoint_schedule'),
        ('app_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='monitor_checkpoint',
            field=models.ManyToManyField(blank=True, to='app_checkpoint.checkpoint', verbose_name='Проходные для монитора'),
        ),
    ]
