# Generated by Django 4.2.7 on 2023-11-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_class', models.CharField(max_length=15, verbose_name='Класс события')),
                ('event_date_time', models.DateTimeField(verbose_name='Дата и время события')),
                ('event_card_hex', models.CharField(max_length=15, verbose_name='Карта инициатор события (hex)')),
                ('event_card_dec', models.CharField(max_length=15, verbose_name='Карта инициатор события dec')),
                ('event_staff', models.CharField(max_length=200, verbose_name='Сотрудник инициатор события')),
                ('event_controller', models.CharField(max_length=200, verbose_name='Контроллер инициатор события')),
                ('event_checkpoint', models.CharField(max_length=200, verbose_name='Проходная иницитор события')),
                ('event_direction', models.CharField(max_length=30, verbose_name='Направление события')),
                ('event_type', models.CharField(blank=True, max_length=5, null=True, verbose_name='Тип события (код от контроллера)')),
                ('event_flag', models.CharField(blank=True, max_length=5, null=True, verbose_name='Флаг события')),
                ('event_granted', models.BooleanField(default=False, verbose_name='Разрешение доступа для события')),
                ('event_package', models.JSONField(default=dict, verbose_name='Присланный пакет события')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
    ]
