# Generated by Django 4.2.7 on 2023-11-24 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_card_dec',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Карта инициатор события dec'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_card_hex',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Карта инициатор события (hex)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_checkpoint',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Проходная иницитор события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_controller',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Контроллер инициатор события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_direction',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Направление события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_staff',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Сотрудник инициатор события'),
        ),
    ]
