# Generated by Django 4.2.7 on 2023-11-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0003_event_event_reason_granted_alter_event_event_granted'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_late_status',
            field=models.CharField(blank=True, default='Без нарушений графика', max_length=250, null=True, verbose_name='Статус опоздания'),
        ),
        migrations.AddField(
            model_name='event',
            name='late',
            field=models.BooleanField(default=False, verbose_name='Опоздание?'),
        ),
    ]
