# Generated by Django 4.2.7 on 2023-11-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0004_event_event_late_status_event_late'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ENTRY_EXIT_queue_broken',
            field=models.BooleanField(default=False, help_text='\n        Данное поле активно в случаях, когда нарушается очередность событий.<br>\n        Например: Сотрудник выходит с территории (ВЫХОД), а события входа (ВХОД)<br>\n        нет в системе за сегодняшний день. И соотвественно наоборот.<br>\n        Всегда ожидается цепочка событий типа: ВХОД -> ВЫХОД -> ВХОД -> ВЫХОД и т.д.\n        ', verbose_name='Нарушение очередности  входа и выхода'),
        ),
        migrations.AlterField(
            model_name='event',
            name='late',
            field=models.BooleanField(default=False, verbose_name='Опоздание??'),
        ),
    ]
