# Generated by Django 4.2.7 on 2023-12-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0005_event_entry_exit_queue_broken_alter_event_late'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_package',
            field=models.JSONField(blank=True, default=dict, verbose_name='Присланный пакет события'),
        ),
    ]
