# Generated by Django 4.2.7 on 2023-12-27 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0006_alter_event_event_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_class',
        ),
    ]
