# Generated by Django 4.2.7 on 2023-11-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_controller', models.CharField(help_text='\n        Дайте контроллеру обдуманное и рациональное имя,<br>\n        которое ВЫ будете дальше использовать в системе в целом.<br>\n        Это важно и для Вашего удобства дальнейшего использования.\n        ', max_length=200, verbose_name='Имя контроллера')),
                ('ip_adress', models.URLField(help_text='\n        Введите адресс программного обеспечения,<br>\n        с которым работают контроллеры.\n        ', verbose_name='URL')),
                ('type_controller', models.CharField(max_length=200, verbose_name='Тип контроллера')),
                ('serial_number', models.CharField(max_length=200, unique=True, verbose_name='Серийный номер контроллера')),
                ('manual_control', models.BooleanField(default=False, help_text='\n        При выборе данного свойства смена ркжима или отключение<br>\n        контроллера возможна только в ручном режиме, через Админ интерфейс.<br>\n        Никакие другие ПО или скрипты не смогут управлять состоянием контроллера.\n        ', verbose_name='Ручное управление')),
                ('controller_activity', models.CharField(choices=[('1', 'active'), ('0', 'desactive')], max_length=2, verbose_name='активность контроллера')),
            ],
        ),
    ]
