# Generated by Django 4.2.7 on 2023-11-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controller', '0002_controller_controller_online_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controller',
            options={'verbose_name': 'Контроллер', 'verbose_name_plural': 'Контроллеры'},
        ),
        migrations.AlterField(
            model_name='controller',
            name='name_controller',
            field=models.CharField(help_text='\n        Дайте контроллеру обдуманное и рациональное имя,<br>\n        которое ВЫ будете дальше использовать в системе в целом.<br>\n        Это важно и для Вашего удобства дальнейшего использования.\n        ', max_length=200, unique=True, verbose_name='Имя контроллера'),
        ),
    ]
