# Generated by Django 4.2.7 on 2023-11-20 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_checkpoint', '0002_alter_checkpoint_name_checpoint'),
        ('app_controller', '0004_alter_controller_controller_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='checkpoint',
            field=models.ForeignKey(blank=True, default=1, help_text='Выберите проходную, к которой приявяжете контроллер.', on_delete=django.db.models.deletion.CASCADE, to='app_checkpoint.checkpoint', verbose_name='Проходная'),
            preserve_default=False,
        ),
    ]
