# Generated by Django 4.2.7 on 2023-11-20 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_checkpoint', '0003_checkpoint_checkpoint_block'),
        ('app_controller', '0005_controller_checkpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='checkpoint',
            field=models.ForeignKey(blank=True, help_text='Выберите проходную, к которой приявяжете контроллер.<br>\n        Контроллер без выбранной проходной не учавствует в логике программы.<br>\n        События с такого контроллера не сохраняются в системе и полностью игнорируются.\n        ', on_delete=django.db.models.deletion.CASCADE, to='app_checkpoint.checkpoint', verbose_name='Проходная'),
        ),
        migrations.AlterField(
            model_name='controller',
            name='controller_online',
            field=models.CharField(default='0/0', max_length=10, verbose_name='Режимы контроллера'),
        ),
    ]
