# Generated by Django 4.2.7 on 2023-11-22 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_checkpoint', '0003_checkpoint_checkpoint_block'),
        ('app_controller', '0006_alter_controller_checkpoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='checkpoint',
            field=models.ForeignKey(blank=True, help_text='Выберите проходную, к которой приявяжете контроллер.<br>\n        Контроллер без выбранной проходной не учавствует в логике программы.<br>\n        События с такого контроллера не сохраняются в системе и полностью игнорируются.\n        ', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_checkpoint.checkpoint', verbose_name='Проходная'),
        ),
        migrations.AlterField(
            model_name='controller',
            name='name_controller',
            field=models.CharField(help_text='\n        Дайте контроллеру обдуманное и рациональное имя,<br>\n        которое ВЫ будете дальше использовать в системе в целом.<br>\n        Это важно и для Вашего удобства дальнейшего использования.\n        ', max_length=200, verbose_name='Имя контроллера'),
        ),
    ]
