# Generated by Django 4.2.7 on 2023-11-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controller', '0007_alter_controller_checkpoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='name_controller',
            field=models.CharField(help_text='\n        Дайте контроллеру обдуманное и рациональное имя,<br>\n        которое ВЫ будете дальше использовать в системе в целом.<br>\n        Это важно и для Вашего удобства дальнейшего использования.\n        ', max_length=200, unique=True, verbose_name='Имя контроллера'),
        ),
    ]
