# Generated by Django 4.2.7 on 2023-11-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controller', '0008_alter_controller_name_controller'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='direction',
            field=models.CharField(default='0', help_text='\n        Установите направление контроллера.<br>\n        Другими словами укажите с каной стороны находится контроллер:<br>\n        со стороны входа или стороны выхода с территории/из помещения т.д.\n        ', max_length=30, verbose_name='Направление'),
        ),
    ]
