# Generated by Django 4.2.7 on 2023-11-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controller', '0009_controller_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='direction',
            field=models.CharField(default='0', help_text='\n        Установите направление контроллера.<br>\n        Другими словами укажите с какой стороны находится контроллер:<br>\n        со стороны входа или стороны выхода с территории/из помещения<br>\n        или же контроллер один на проходную (Контроллер на ВХОД и ВЫХОД).\n        ', max_length=30, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='controller',
            name='name_controller',
            field=models.CharField(help_text='\n        Дайте контроллеру обдуманное и рациональное имя,<br>\n        которое ВЫ будете дальше использовать в системе в целом.<br>\n        Это важно и для Вашего удобства дальнейшего использования.\n        ', max_length=200, verbose_name='Имя контроллера'),
        ),
    ]
