# Generated by Django 4.2.7 on 2023-11-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controller', '0010_alter_controller_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='direction',
            field=models.CharField(blank=True, default='0', help_text='\n        Установите направление контроллера.<br>\n        Другими словами укажите с какой стороны находится контроллер:<br>\n        со стороны входа или стороны выхода с территории/из помещения<br>\n        или же контроллер один на проходную (Контроллер на ВХОД и ВЫХОД).\n        ', max_length=30, verbose_name='Направление'),
        ),
    ]
