# Generated by Django 4.2.7 on 2023-12-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controller', '0012_remove_controller_controller_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='controller_mode',
            field=models.CharField(default='0', max_length=10, verbose_name='Режим контроллера'),
        ),
        migrations.AddField(
            model_name='controller',
            name='controller_online',
            field=models.CharField(default='0', max_length=10, verbose_name='Режимы контроллера'),
        ),
    ]
