# Generated by Django 4.2.7 on 2023-12-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controller', '0013_controller_controller_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='controller_activity',
            field=models.CharField(default='1', help_text='\n        Выбирите состояние контроллера и сохраните его <br>\n        для включения или выключения.\n        ', max_length=10, verbose_name='Состояние контроллера'),
        ),
        migrations.AlterField(
            model_name='controller',
            name='controller_mode',
            field=models.CharField(default='1', max_length=10, verbose_name='Режим контроллера'),
        ),
        migrations.AlterField(
            model_name='controller',
            name='controller_online',
            field=models.CharField(default='1', max_length=10, verbose_name='Режимы контроллера'),
        ),
    ]
