# Generated by Django 4.2.7 on 2023-11-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_position', models.CharField(max_length=150, unique=True, verbose_name='Название должности')),
                ('desc_position', models.TextField(verbose_name='Описание должности')),
                ('tag', models.ManyToManyField(blank=True, help_text='\n        Выбирите/добавьте уникальный Тег для должности для создание особых групп.\n        Должности могут содержать информацию о разной степени (это категории, разряды и тому подобно).\n        За счет Тегов можно обьединить все разряды (Например: монтажник 1р, монтажник 2р) дав им Тег Монтажники\n        ', to='app_tag.tags', verbose_name='ТЕГ')),
            ],
        ),
    ]
