# Generated by Django 4.2.7 on 2023-11-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tag', '0001_initial'),
        ('app_position', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterField(
            model_name='position',
            name='tag',
            field=models.ManyToManyField(blank=True, help_text='\n        Выбирите/добавьте уникальный Тег для должности для создание особых групп.<br>\n        Должности могут содержать информацию о разной степени (это категории, разряды и тому подобно).<br>\n        За счет Тегов можно обьединить все разряды (Например: монтажник 1р, монтажник 2р), дав им Тег Монтажники.<br>\n        <br>\n        ', to='app_tag.tags', verbose_name='ТЕГ'),
        ),
    ]
