# Generated by Django 4.2.7 on 2023-11-14 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('patromic', models.CharField(blank=True, max_length=150, verbose_name='Фамилия')),
                ('interception', models.BooleanField(default=False, help_text='Ограничит доступ на всех проходных/контроллерах', verbose_name='Перехват')),
                ('phone_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(regex='^\\+7\\d{10}$')], verbose_name='Телефонный номер')),
                ('home_adress', models.CharField(max_length=300, verbose_name='Домашний адресс')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
