# Generated by Django 4.2.7 on 2023-11-14 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_staffs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='home_adress',
            field=models.CharField(blank=True, max_length=300, verbose_name='Домашний адресс'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(regex='^\\+7\\d{10}$')], verbose_name='Телефонный номер'),
        ),
    ]
