# Generated by Django 4.2.7 on 2023-11-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_staffs', '0002_alter_staff_home_adress_alter_staff_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='patromic',
            field=models.CharField(blank=True, max_length=150, verbose_name='Отчество'),
        ),
    ]
