# Generated by Django 4.2.7 on 2023-11-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tag', '0001_initial'),
        ('app_staffs', '0005_alter_staff_without_biometric_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='tag',
            field=models.ManyToManyField(blank=True, help_text='Выбирите/добавьте уникальный Тег для сотрудника для создание особых групп сотрудников', to='app_tag.tags', verbose_name='ТЕГ'),
        ),
    ]
