# Generated by Django 4.2.7 on 2023-11-16 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_position', '0002_alter_position_options_alter_position_tag'),
        ('app_tag', '0001_initial'),
        ('app_staffs', '0007_alter_staff_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_position.position', verbose_name='Долность'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='tag',
            field=models.ManyToManyField(blank=True, help_text='\n        Выбирите/добавьте уникальный Тег для сотрудника для создание особых групп сотрудников.<br>\n        Добавляйте сотруднику сколько угодно Тегов, включая его в разные группы.<br><br>\n        ', to='app_tag.tags', verbose_name='ТЕГ'),
        ),
    ]
