# Generated by Django 4.2.7 on 2023-11-16 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_position', '0002_alter_position_options_alter_position_tag'),
        ('app_staffs', '0008_staff_position_alter_staff_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_position.position', verbose_name='Долность'),
        ),
    ]
