# Generated by Django 4.2.7 on 2023-11-20 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_access_profile', '0002_accessprofile_checpoint'),
        ('app_staffs', '0011_staff_departament'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='access_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_access_profile.accessprofile', verbose_name='Профиль доступа'),
            preserve_default=False,
        ),
    ]
