# Generated by Django 4.2.7 on 2023-11-14 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_staffs', '0003_alter_staff_patromic'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_card_dec_format', models.CharField(max_length=10, unique=True, verbose_name='Номер пропуска в DEC формате')),
                ('pass_cart_hex_format', models.CharField(max_length=10, unique=True, verbose_name='Номер пропуска в HEX формате')),
                ('activate_card', models.BooleanField(default=True, help_text='Отключите, если не хотите, чтобы сотрудник использовал данную карту', verbose_name='Активировать карту')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_staffs.staff', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Карта/Пропуск',
                'verbose_name_plural': 'Карты/Пропуски',
            },
        ),
    ]
