# Generated by Django 4.2.7 on 2023-11-14 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_staffs', '0003_alter_staff_patromic'),
        ('app_card_pass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardpass',
            name='staff',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_staffs.staff', verbose_name='Сотрудник'),
        ),
    ]
