# Generated by Django 4.2.7 on 2023-11-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_card_pass', '0003_alter_cardpass_pass_cart_hex_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardpass',
            name='activate_card',
            field=models.BooleanField(blank=True, default=True, help_text='Отключите, если не хотите, чтобы сотрудник использовал данную карту', verbose_name='Активировать карту'),
        ),
    ]
