# Generated by Django 4.2.7 on 2023-11-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_card_pass', '0004_alter_cardpass_activate_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardpass',
            name='activate_card',
            field=models.BooleanField(default=True, help_text='Отключите, если не хотите, чтобы сотрудник использовал данную карту', verbose_name='Активировать карту'),
        ),
        migrations.AlterField(
            model_name='cardpass',
            name='pass_cart_hex_format',
            field=models.CharField(blank=True, max_length=10, verbose_name='Номер пропуска в HEX формате'),
        ),
    ]
