# Generated by Django 4.2.7 on 2023-11-14 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_staffs', '0003_alter_staff_patromic'),
        ('app_card_pass', '0006_alter_cardpass_pass_cart_hex_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardpass',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_staffs.staff', verbose_name='Сотрудник'),
        ),
    ]
