# Generated by Django 4.2.7 on 2023-11-15 07:34

import app_card_pass.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_card_pass', '0012_alter_cardpass_pass_cart_hex_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardpass',
            name='pass_card_dec_format',
            field=models.CharField(max_length=10, unique=True, validators=[app_card_pass.models.pass_card_dec_format_valid], verbose_name='Номер пропуска в DEC формате'),
        ),
    ]
