# Generated by Django 4.2.7 on 2023-11-16 05:54

import app_tag.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_tad', app_tag.models.ColorField(default='#FF0000', max_length=7, unique=True, verbose_name='Цвет тега')),
                ('name_tag', models.CharField(max_length=150, unique=True, verbose_name='Название тега')),
                ('desc_tag', models.TextField(blank=True, max_length=1500, verbose_name='Описание тега')),
                ('interception', models.BooleanField(default=False, help_text='Ограничит доступ данному Тегу на всех проходных/контроллерах', verbose_name='Перехват')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
    ]
