# Generated by Django 4.2.7 on 2023-11-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_checpoint', models.CharField(help_text='\n        В данном поле задается имя проходной<br>\n        Будьте разумны в наименовании проходных, так как от их имен будете отталкиваться<br>\n        отталкиваться в будущем для создания профилей доступа.\n        ', max_length=200, unique=True, verbose_name='Имя проходной')),
                ('desc_checkpoint', models.TextField(blank=True, verbose_name='Описание проходной')),
            ],
            options={
                'verbose_name': 'Проходная',
                'verbose_name_plural': 'Проходные',
            },
        ),
    ]
