# Generated by Django 4.2.7 on 2023-11-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_checkpoint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpoint',
            name='name_checpoint',
            field=models.CharField(help_text='\n        В данном поле задается имя проходной<br>\n        Будьте разумны в наименовании проходных, так как от их имен будете<br>\n        отталкиваться в будущем для создания профилей доступа.\n        ', max_length=200, unique=True, verbose_name='Имя проходной'),
        ),
    ]
