# Generated by Django 4.2.7 on 2023-11-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_checkpoint', '0002_alter_checkpoint_name_checpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='checkpoint_block',
            field=models.BooleanField(default=False, help_text='\n        Установив данный параметр, Вы заблокируете контроллеры данной проходной.<br>\n        Данный выбор не возможен, если хоть один контроллер проходной имеет флаг<br>\n        -->> "Ручное управление" <<--\n        ', verbose_name='Заблокировать проходную?'),
        ),
    ]
