# Generated by Django 4.2.7 on 2023-11-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_access_profile', models.CharField(help_text='\n        Придумайте название профиля доступа максимально описавающее его уровень<br>\n        доступа на проходные. Например: "Полный доступ" - доступ разрешен через все проходные,<br>\n        "Только вход на территорию", "Корпус 99", "Комната 67", "3 этаж", "Ангар 43".<br>\n        ', max_length=200, unique=True, verbose_name='Название профиля доступа')),
                ('desc_access_profile', models.TextField(blank=True, verbose_name='Описание профиля')),
                ('block_access_profile', models.BooleanField(default=False, help_text='\n        Выбрав данный параметр, все сотрудники, имеющий данный профиль доступа<br>\n        не смогут пользоваться своими пропусками на проходных.<br>\n        Их пропуска будут стерты из контроллеров, а проходные для них станут не доступны!<br>\n        Использовать при явной необходимости, для перехвата большого колличества сотрудников!\n        ', verbose_name='Заблокировать профиль?')),
            ],
            options={
                'verbose_name': 'Профиль доступа',
                'verbose_name_plural': 'Профиля доступа',
            },
        ),
    ]
