# Generated by Django 4.2.7 on 2023-11-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_checkpoint', '0003_checkpoint_checkpoint_block'),
        ('app_access_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessprofile',
            name='checpoint',
            field=models.ManyToManyField(help_text='\n        Выбирите проходные, куда данный профиль доступа будет иметь доступ.\n        ', to='app_checkpoint.checkpoint', verbose_name='Проходные'),
        ),
    ]
