# Generated by Django 4.2.7 on 2023-11-15 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_staffs', '0003_alter_staff_patromic'),
        ('app_photo_staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImage',
            new_name='StaffPhoto',
        ),
    ]
