# Generated by Django 4.2.7 on 2023-11-16 04:24

import app_photo_staff.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_photo_staff', '0002_rename_productimage_staffphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffphoto',
            name='photo',
            field=models.ImageField(upload_to=app_photo_staff.models.get_path_file, verbose_name='Фотография'),
        ),
    ]
